### ISSUE TITLE
error received with a memory dump for win 10 v1809

### ISSUE THREAD

**Issue by gittestshay** [mandiant/win10_rekall#1]
Hi, 
I received the below error when trying to analyze a memory dump captured from a win10 v1809 x64 image captured by FTK imager. could you please help?

(MyEnv) root@kali:/media/usb# rekal -f memdump.mem  imageinfo
No handlers could be found for logger "rekall.plugins.tools"
Traceback (most recent call last):               
  File "/tmp/MyEnv/bin/rekal", line 11, in <module>
    load_entry_point('rekall-core', 'console_scripts', 'rekal')()
  File "/root/win10_rekall/rekall-core/rekall/rekal.py", line 98, in main
    user_session=user_session)
  File "/root/win10_rekall/rekall-core/rekall/args.py", line 432, in parse_args
    command_metadata = user_session.plugins.Metadata(plugin_name)
  File "/root/win10_rekall/rekall-core/rekall/session.py", line 142, in Metadata
    return self.plugin_db.GetActivePlugin(name)
  File "/root/win10_rekall/rekall-core/rekall/plugin.py", line 986, in GetActivePlugin
    if plugin_cls.is_active(self.session):
  File "/root/win10_rekall/rekall-core/rekall/plugin.py", line 434, in is_active
    profile = (session.profile != None and
  File "/root/win10_rekall/rekall-lib/rekall_lib/utils.py", line 1093, in __get__
    return super(safe_property, self).__get__(*args, **kwargs)
  File "/root/win10_rekall/rekall-core/rekall/session.py", line 1066, in profile
    res = self.GetParameter("profile_obj")
  File "/root/win10_rekall/rekall-core/rekall/session.py", line 768, in GetParameter
    result = self._RunParameterHook(item)
  File "/root/win10_rekall/rekall-core/rekall/session.py", line 807, in _RunParameterHook
    result = hook.calculate()
  File "/root/win10_rekall/rekall-core/rekall/plugins/guess_profile.py", line 762, in calculate
    profile_obj = self.ScanProfiles()
  File "/root/win10_rekall/rekall-core/rekall/plugins/guess_profile.py", line 630, in ScanProfiles
    return self._ScanProfiles()
  File "/root/win10_rekall/rekall-core/rekall/plugins/guess_profile.py", line 688, in _ScanProfiles
    profile = method.DetectFromHit(hit, offset, address_space)
  File "/root/win10_rekall/rekall-core/rekall/plugins/guess_profile.py", line 383, in DetectFromHit
    return self._test_rsds(rsds)
  File "/root/win10_rekall/rekall-core/rekall/plugins/guess_profile.py", line 388, in _test_rsds
    profile = self.VerifyProfile("nt/GUID/%s" % rsds.GUID_AGE)
  File "/root/win10_rekall/rekall-core/rekall/plugins/guess_profile.py", line 362, in VerifyProfile
    return self._ApplyFindDTB(self.find_dtb_impl, profile)
  File "/root/win10_rekall/rekall-core/rekall/plugins/guess_profile.py", line 99, in _ApplyFindDTB
    for address_space in find_dtb_plugin.address_space_hits():
  File "/root/win10_rekall/rekall-core/rekall/plugins/windows/common.py", line 130, in address_space_hits
    address_space = self.VerifyHit(dtb)
  File "/root/win10_rekall/rekall-core/rekall/plugins/windows/common.py", line 195, in VerifyHit
    return self.CreateAS(dtb)
  File "/root/win10_rekall/rekall-core/rekall/plugins/core.py", line 269, in CreateAS
    profile=self.profile)
  File "/root/win10_rekall/rekall-lib/rekall_lib/registry.py", line 96, in __call__
    res = super(UniqueObjectIdMetaclass, cls).__call__(*args, **kwargs)
  File "/root/win10_rekall/rekall-core/rekall/plugins/windows/win10_memcompression.py", line 314, in __init__
    super().__init__(**kwargs)
TypeError: super() takes at least 1 argument (0 given)

**Comment by hanxu-a** [comment]
I also encountered the same problem, did you solve the problem?
